base_frame: "base_footprint"
bounding_box:
  min_x: 0.0
  max_x: 5.0
  min_y: -3.0
  max_y: 3.0
  min_z: -1.0
  max_z: 1.0
ransac: # disable ransac of bounding box excludes the ground already
  use_ransac: true
  distance_threshold: 0.01
  max_iterations: 100
clustering:
  cluster_tolerance: 0.02
  min_cluster_size: 20
  max_cluster_size: 10000
final_filter:
  min_side_length: 0.01
  max_side_length: 0.4
  min_height: 0.02
  max_height: 0.2
